name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SWIFT_VERSION: '5.9'

jobs:
  # macOS build and test
  macos:
    name: macOS (Swift ${{ matrix.swift }})
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ['5.9']
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
      - name: Swift version
        run: swift --version
      
      - name: Build
        run: swift build -v
      
      - name: Run tests
        run: swift test -v
        
      - name: Build CLI
        run: swift build --product speedrun-cli -c release
        
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: speedrun-cli-macos
          path: .build/release/speedrun-cli

  # Linux build and test (native)
  linux:
    name: Linux (Swift 5.9)
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    steps:
      - uses: actions/checkout@v4
      
      - name: Swift version
        run: swift --version
        
      - name: Build
        run: swift build -v
        
      - name: Run tests
        run: swift test -v
        
      - name: Build CLI
        run: swift build --product speedrun-cli -c release
        
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: speedrun-cli-linux
          path: .build/release/speedrun-cli

  # Docker build and test
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: speedrunkit:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Docker build
        run: |
          docker build -t speedrunkit:test .
          docker run --rm speedrunkit:test || true

